<<<<<<< HEAD
# Generated by Django 4.2.3 on 2023-10-08 07:01
=======
# Generated by Django 4.2.3 on 2023-10-09 05:06
>>>>>>> slave

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_alter_product_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt',
<<<<<<< HEAD
            field=models.FileField(null=True, upload_to='orders/receipts/'),
=======
            field=models.FileField(null=True, upload_to='orders/receipts'),
>>>>>>> slave
        ),
    ]
