# Generated by Django 4.2.3 on 2023-11-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0010_alter_product_description_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='orders/receipts/'),
        ),
    ]
